/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package justalk.server.gui;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import justalk.client.gui.LoginForm;
import justalk.server.Server;

/**
 *
 * @author User
 */
@SuppressWarnings("serial")
public class ServerForm extends javax.swing.JFrame {

    // Default Information
    public static String DEFAULT_HOST = "host";
    public static int DEFAULT_PORT = 1337;
    
    //public static String USERNAME;
        
    private int port;
    private Server server;
    
    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        serverAddressTextField.setEnabled(false);
        serverPortTextField.setEnabled(true);
        
        try {
            Image i = ImageIO.read(getClass().getResource(""));
            setIconImage(i);
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        iconPanel = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        connectionPanel = new javax.swing.JPanel();
        serverAdressLabel = new javax.swing.JLabel();
        serverAddressTextField = new javax.swing.JTextField();
        serverPortLabel = new javax.swing.JLabel();
        serverPortTextField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        connectionStatusPanel = new javax.swing.JPanel();
        connectionLabel = new javax.swing.JLabel();
        connectionStatusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        contentPanel.setLayout(new java.awt.BorderLayout());

        iconPanel.setLayout(new java.awt.BorderLayout());

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(""))); // NOI18N
        iconPanel.add(iconLabel, java.awt.BorderLayout.CENTER);

        contentPanel.add(iconPanel, java.awt.BorderLayout.WEST);

        mainPanel.setLayout(new java.awt.BorderLayout());

        connectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Server (IP and Port)"));
        connectionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        serverAdressLabel.setText("IP Address:");
        serverAdressLabel.setPreferredSize(new java.awt.Dimension(60, 14));
        connectionPanel.add(serverAdressLabel);

        serverAddressTextField.setText(DEFAULT_HOST);
        serverAddressTextField.setPreferredSize(new java.awt.Dimension(180, 20));
        connectionPanel.add(serverAddressTextField);

        serverPortLabel.setText("Port:");
        connectionPanel.add(serverPortLabel);

        serverPortTextField.setText(DEFAULT_PORT+"");
        serverPortTextField.setMinimumSize(null);
        serverPortTextField.setPreferredSize(new java.awt.Dimension(50, 20));
        connectionPanel.add(serverPortTextField);

        startButton.setText("Start");
        startButton.setPreferredSize(new java.awt.Dimension(100, 23));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        connectionPanel.add(startButton);

        mainPanel.add(connectionPanel, java.awt.BorderLayout.PAGE_START);

        connectionStatusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        connectionStatusPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        connectionLabel.setText("Server Status:");
        connectionStatusPanel.add(connectionLabel);

        connectionStatusLabel.setForeground(java.awt.Color.red);
        connectionStatusLabel.setText("Shutdown");
        connectionStatusPanel.add(connectionStatusLabel);

        mainPanel.add(connectionStatusPanel, java.awt.BorderLayout.PAGE_END);

        contentPanel.add(mainPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(contentPanel, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        if (startButton.getText().equals("Start") && checkConnectInput()) {
            server = new Server(port);
            server.start();
            startButton.setText("Shutdown");
            serverPortTextField.setEnabled(false);
            setConnectionStatus("Running", Color.GREEN);
        } else if(startButton.getText().equals("Shutdown")) {
           server.shutdown();
           startButton.setText("Start");
           serverPortTextField.setEnabled(true);
            setConnectionStatus("Shutdown");
        }
    }//GEN-LAST:event_startButtonActionPerformed

    
    private boolean checkConnectInput() {
        if (!connectionStatusLabel.getText().equals("")) {
            connectionStatusLabel.setText("");
        }
               
        if (!serverPortTextField.getText().equals("")) {
            if (serverPortTextField.getText().matches("[0-9]*")) {
                port = Integer.parseInt(serverPortTextField.getText());
            } else {
                setConnectionStatus("Port must be number!");
                return false;
            }
        } else {
            setConnectionStatus("Port required!");
            return false;
        }
        return true;
    }
    
    public void setConnectionStatus(String status) {
        connectionStatusLabel.setForeground(Color.red);
        connectionStatusLabel.setText(status);
    }
    
    public void setConnectionStatus(String status, Color color) {
        connectionStatusLabel.setForeground(color);
        connectionStatusLabel.setText(status);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connectionLabel;
    private javax.swing.JPanel connectionPanel;
    private javax.swing.JLabel connectionStatusLabel;
    private javax.swing.JPanel connectionStatusPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField serverAddressTextField;
    private javax.swing.JLabel serverAdressLabel;
    private javax.swing.JLabel serverPortLabel;
    private javax.swing.JTextField serverPortTextField;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
